apiVersion: argoproj.io/v1alpha1
kind: ArgoCDExtension
metadata: 
  name: analysis-run
  finalizers: 
    - extensions-finalizer.argocd.argoproj.io
spec: 
  sources: 
  - web: 
      url: https://github.com/satyakiran-opsmx/rollout-extension/releases/download/v1.0.4/extension.tar
      